name: Staging --> Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:  
      - name: Copy from Staging to Production
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: | 
            rsync -av --exclude="node_modules" --exclude=".ftp-deploy-sync-state.json" /home/${{ secrets.USER }}/wxr-server-staging/. /home/${{ secrets.USER }}/public_html/weightxreps.net/wxr-server-2/ 
            source /home/${{ secrets.USER }}/nodevenv/public_html/weightxreps.net/wxr-server-2/14/bin/activate
            cd /home/${{ secrets.USER }}/public_html/weightxreps.net/wxr-server-2
            npm i 
            nohup kill $(ps aux | grep "wxr-server-2" | awk '{print $2}') 2> /dev/null || echo "It was not running... anyway..."